### ISSUE TITLE
Format VSCode with cblack

### ISSUE THREAD

**Issue by jorislimonier** [pausan/cblack#19]
Hi, how can I make VSCode format with cblack?

VSCode allows me to choose my python formatter from a list that doesn't include cblack. The advantage of using cblack from VSCode, as opposed to CLI is that I can quickly format with a shortcut as I'm coding,  no need to change window and type a shell command.

Cheers,
JL.

**Comment by Attila94** [comment]
In your VSCode settings choose black from the dropdown list and then change the Black Path to your cblack binary.

**Comment by jorislimonier** [comment]
That worked, thanks! Such an easy solution, I should have thought about it.

**Comment by AhnafHamim** [comment]
> That worked, thanks! Such an easy solution, I should have thought about it.

sorry im a newbie when it comes to python. Could you send a screenshot or provide a little more detail on what path exactly you changed to? Thank you

**Comment by jorislimonier** [comment]
Go to settings, search "black path" and update it accordingly
