### ISSUE TITLE
module 'black' has no attribute 'fix_docstring'

### ISSUE THREAD

**Issue by sztomi** [pausan/cblack#3]
This is broken with `black==21.5b1`, but pinning to `black==20.8b1` fixes it (I did not bisect the exact version where it breaks, I simply checked the version that was spelled out in the setup.py). 

Regardless of the issue, maybe it would make sense to strictly pin the required black version for cblack? Otherwise this can happen at any time. Alternatively, pin to `black==20.*` which will only bump minor versions, not the major component.

**Comment by pausan** [comment]
Hey! Thanks for your comment and sorry for the late reply. Your issue & solution make total sense to prevent the tool from breaking in the future.

I have pinned **cblack** to the current latest **black** version and increased **cblack** the version to 0.9.2 which includes the changes by @bukzor to add compatibility to **black** 21.5.

The package has been uploaded to pypi as of 5 min ago.
